# This workflow will run a set of scripts to check package functionality

on: [push]
name: check-pkg

jobs:
  check_all:
     runs-on: windows-latest
     env:
       GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

     steps: 
       - uses: actions/checkout@v2
       - uses: r-lib/actions/setup-r@v2
       - name: Install dependencies
         run: | 
          cd scripts
          Rscript install_dependencies.R
       - uses: r-lib/actions/setup-tinytex@v2
       - name: Check package
         run: |
          cd scripts 
          Rscript check_local.R
