# This workflow will run a set of scripts to check package functionality

on: [push]
name: check-pkg

jobs:
  install_dependencies:
     runs-on: ubuntu-latest
     steps: 
       - uses: actions/checkout@v2
       - uses: r-lib/actions/setup-r@v2
       - name: Install dependencies
         run: | 
          cd scripts
          Rscript install_dependencies.R
